name: All Build Start UP

on:
  workflow_dispatch:
    inputs:
      BATCH:
        description: "9个分批并行-选择分支(1-3)"
        required: true
        default: "1"

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Matrix from FILE List
        id: set-matrix
        run: |
          BATCH="${{ github.event.inputs.BATCH }}"
          if [[ "$BATCH" == "1" ]]; then
            FILE_LIST=(
              "oneplus_nord_ce4_lite_5g_v"
              "oneplus_nord_ce4_v"
              "oneplus_nord_4_v"
              "oneplus_ace_3v_v"
              "oneplus_10_pro_v"
              "oneplus_10t_v"
              "oneplus_11r_v"
              "oneplus_ace2_v"
              "oneplus_ace_pro_v"
            )
          elif [[ "$BATCH" == "2" ]]; then
            FILE_LIST=(
              "oneplus_11_v"
              "oneplus_12r_v"
              "oneplus_ace2_pro_v"
              "oneplus_ace3_v"
              "oneplus_open_v"
              "oneplus12_v"
              "oneplus_13r"
              "oneplus_ace3_pro_v"
              "oneplus_ace5"
            )
          elif [[ "$BATCH" == "3" ]]; then
            FILE_LIST=(
              "oneplus_pad_pro_v"
              "oneplus_pad2_v"
              "oneplus_ace5_pro"
              "oneplus_13"
              "oneplus_13t"
              "oneplus_13s"
              "oneplus_pad_2_pro"
              "oneplus_pad_3"
            )
          else
            echo "无效的 BATCH 值: $BATCH"
            exit 1
          fi

          MATRIX_JSON=$(printf '%s\n' "${FILE_LIST[@]}" | jq -R -s -c '
            split("\n")[:-1] |
            map({
              file: .,
              enable_sched: (
                . == "oneplus_pad_3" or
                . == "oneplus_pad_2_pro" or
                . == "oneplus_13" or
                . == "oneplus_13t" or
                . == "oneplus_ace5_pro"
              )
            })
          ')
          echo "matrix=$MATRIX_JSON" >> $GITHUB_OUTPUT

  build:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - name: Call Original Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build OnePlus_SukiSU Ultra All
          token: ${{ secrets.GITHUB_TOKEN }}
          inputs: |
            {
              "FILE": "${{ matrix.file }}",
              "SUSFS_CI": "CI",
              "KSU_META": "susfs-main/Numbersf",
              "BUILD_TIME": "F",
              "SUFFIX": "",
              "FAST_BUILD": "true",
              "VFS": "true",
              "KPM": "true",
              "SCHED": "${{ matrix.enable_sched }}",
              "ZRAM": "false"
            }

  wait-and-download:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Builds to Finish
        run: |
          echo "等待35分钟以确保构建完成..."
          sleep 2100

      - name: Setup gh CLI
        run: |
          sudo apt update && sudo apt install -y gh zip
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Download Artifacts from Current Batch
        run: |
          mkdir -p all_artifacts

          BATCH="${{ github.event.inputs.BATCH }}"
          if [[ "$BATCH" == "1" ]]; then
            FILE_LIST=(
              "oneplus_nord_ce4_lite_5g_v"
              "oneplus_nord_ce4_v"
              "oneplus_nord_4_v"
              "oneplus_ace_3v_v"
              "oneplus_10_pro_v"
              "oneplus_10t_v"
              "oneplus_11r_v"
              "oneplus_ace2_v"
              "oneplus_ace_pro_v"
            )
          elif [[ "$BATCH" == "2" ]]; then
            FILE_LIST=(
              "oneplus_11_v"
              "oneplus_12r_v"
              "oneplus_ace2_pro_v"
              "oneplus_ace3_v"
              "oneplus_open_v"
              "oneplus12_v"
              "oneplus_13r"
              "oneplus_ace3_pro_v"
              "oneplus_ace5"
            )
          elif [[ "$BATCH" == "3" ]]; then
            FILE_LIST=(
              "oneplus_pad_pro_v"
              "oneplus_pad2_v"
              "oneplus_ace5_pro"
              "oneplus_13"
              "oneplus_13t"
              "oneplus_13s"
              "oneplus_pad_2_pro"
              "oneplus_pad_3"
            )
          else
            echo "无效的 BATCH 值: $BATCH"
            exit 1
          fi

      - name: Clean ccache After Build
        run: |
          echo "Cleaning ccache for $HOME/.ccache_${{ matrix.file }} ..."
          rm -rf "$HOME/.ccache_${{ matrix.file }}"

      - name: List Matching Artifacts
        id: list-artifacts
        run: |
          echo "查找所有包含 'AnyKernel3_SukiSUUltra' 的 artifact 名称..."
          ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts --jq '.artifacts[] | select(.name | contains("AnyKernel3_SukiSUUltra")) | .name')
          echo "找到以下 artifact 名称："
          echo "$ARTIFACTS"
          echo "ARTIFACT_NAMES=$(echo "$ARTIFACTS" | tr '\n' ';')" >> $GITHUB_OUTPUT

      - name: Download All Matched Artifacts
        run: |
          mkdir -p all_artifacts
          IFS=';' read -ra NAMES <<< "${{ steps.list-artifacts.outputs.ARTIFACT_NAMES }}"
          for NAME in "${NAMES[@]}"; do
            if [[ -n "$NAME" ]]; then
              echo "下载 artifact: $NAME"
              gh run download --name "$NAME" --dir "all_artifacts/$NAME" || echo "下载失败，跳过 $NAME"
            fi
          done

      - name: Zip All Downloaded Artifacts
        run: |
          zip -r All-AnyKernel3-SukiSUUltra.zip all_artifacts

      - name: Upload combined ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: All-AnyKernel3-SukiSUUltra
          path: All-AnyKernel3-SukiSUUltra.zip