name: 清理工作流运行记录

on:
  workflow_dispatch:
    inputs:
      repo:
        description: '要清理的仓库（格式：用户名/仓库名）'
        required: true
      count:
        description: '要检查的最多运行次数'
        required: false
        default: '20'
      delete_failed:
        description: '是否删除失败的运行记录？(true/false)'
        required: false
        default: 'true'
      delete_success:
        description: '是否删除成功的运行记录？(true/false)'
        required: false
        default: 'false'
      delete_cancelled:
        description: '是否删除已取消的运行记录？(true/false)'
        required: false
        default: 'false'
      workflow_name:
        description: '要清理的工作流名称'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 安装 GitHub CLI
        run: sudo apt-get install gh -y

      - name: 使用 GITHUB_TOKEN 进行认证
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: 获取工作流 ID 和删除运行记录
        env:
          REPO: ${{ inputs.repo }}
          COUNT: ${{ inputs.count }}
          DELETE_FAILED: ${{ inputs.delete_failed }}
          DELETE_SUCCESS: ${{ inputs.delete_success }}
          DELETE_CANCELLED: ${{ inputs.delete_cancelled }}
          WORKFLOW_NAME: ${{ inputs.workflow_name }}
        run: |
          # 获取指定工作流的 ID
          WORKFLOW_API_RESPONSE=$(gh api repos/$REPO/actions/workflows)
          echo "工作流 API 响应: $WORKFLOW_API_RESPONSE"
          
          WORKFLOW_ID=$(echo "$WORKFLOW_API_RESPONSE" | jq -r ".workflows[] | select(.name == \"$WORKFLOW_NAME\") | .id")

          if [ -z "$WORKFLOW_ID" ]; then
            echo "未找到指定工作流！"
            exit 1
          fi

          # 删除运行记录
          RUNS_API_RESPONSE=$(gh api "repos/$REPO/actions/workflows/$WORKFLOW_ID/runs?per_page=$COUNT")
          echo "运行记录 API 响应: $RUNS_API_RESPONSE"
          
          echo "$RUNS_API_RESPONSE" | jq -c '.workflow_runs[]' \
          | while read run; do
              ID=$(echo "$run" | jq -r '.id')
              STATUS=$(echo "$run" | jq -r '.conclusion')

              # 根据用户输入的条件决定是否删除该记录
              if [[ "$STATUS" == "failure" && "$DELETE_FAILED" != "true" ]]; then continue; fi
              if [[ "$STATUS" == "success" && "$DELETE_SUCCESS" != "true" ]]; then continue; fi
              if [[ "$STATUS" == "cancelled" && "$DELETE_CANCELLED" != "true" ]]; then continue; fi

              echo "正在删除运行记录 ID: $ID (状态: $STATUS)"
              gh api -X DELETE repos/$REPO/actions/runs/$ID
          done