name: 清理工作流运行记录

on:
  workflow_dispatch:
    inputs:
      repo:
        description: '清理的仓库(格式:用户名/仓库名)'
        required: true
        default: 'Numbersf/Action-Build'
      workflow_name:
        description: '清理的工作流名称'
        required: true
        default: 'Build OnePlus_SukiSU Ultra All'
      count:
        description: '检查的最多运行次数'
        required: false
        default: '20'
      delete_failed:
        description: '删除失败的运行记录？'
        required: false
        type: boolean
        default: true
      delete_success:
        description: '删除成功的运行记录？'
        required: false
        type: boolean
        default: false
      delete_cancelled:
        description: '删除已取消的运行记录？'
        required: false
        type: boolean
        default: false

permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: 安装 GitHub CLI
        run: sudo apt-get install gh -y

      - name: 安装 jq（用于解析 JSON）
        run: sudo apt-get install jq -y

      - name: 使用 GITHUB_TOKEN 进行认证
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: 清理运行记录
        env:
          REPO: ${{ inputs.repo }}
          COUNT: ${{ inputs.count }}
          DELETE_FAILED: ${{ inputs.delete_failed }}
          DELETE_SUCCESS: ${{ inputs.delete_success }}
          DELETE_CANCELLED: ${{ inputs.delete_cancelled }}
          WORKFLOW_NAME: ${{ inputs.workflow_name }}
        run: |
          set -e

          cleanup_workflow_runs() {
            local TARGET_WORKFLOW_NAME="$1"

            echo "正在查找工作流 \"$TARGET_WORKFLOW_NAME\" 的 ID..."
            TARGET_WORKFLOW_ID=$(gh api repos/$REPO/actions/workflows | jq -r ".workflows[] | select(.name == \"$TARGET_WORKFLOW_NAME\") | .id")

            if [ -z "$TARGET_WORKFLOW_ID" ]; then
              echo "未找到名为 \"$TARGET_WORKFLOW_NAME\" 的工作流！"
              return
            fi

            echo "找到工作流 ID: $TARGET_WORKFLOW_ID"
            echo "正在获取最近 $COUNT 条运行记录..."

            CURRENT_RUN_ID="${{ github.run_id }}"
            RUNS=$(gh api "repos/$REPO/actions/workflows/$TARGET_WORKFLOW_ID/runs?per_page=$COUNT" | jq -c '.workflow_runs[]')

            echo "$RUNS" | while read run; do
              ID=$(echo "$run" | jq -r '.id')
              STATUS=$(echo "$run" | jq -r '.conclusion')
              STATE=$(echo "$run" | jq -r '.status')

              if [[ "$ID" == "$CURRENT_RUN_ID" ]]; then
                echo "跳过当前运行 ID: $ID"
                continue
              fi

              if [[ "$STATE" == "in_progress" || "$STATE" == "queued" ]]; then
                echo "跳过运行 ID: $ID（状态为 $STATE）"
                continue
              fi

              if [[ "$STATUS" == "failure" && "$DELETE_FAILED" != "true" ]]; then continue; fi
              if [[ "$STATUS" == "success" && "$DELETE_SUCCESS" != "true" ]]; then continue; fi
              if [[ "$STATUS" == "cancelled" && "$DELETE_CANCELLED" != "true" ]]; then continue; fi

              echo "删除运行记录 ID: $ID (状态: $STATUS)"
              gh api -X DELETE "repos/$REPO/actions/runs/$ID" || echo "删除失败（可能权限不足或 ID 不存在）"
            done
          }

          # 1. 清理用户指定的工作流（如编译内核）
          cleanup_workflow_runs "$WORKFLOW_NAME"

          # 2. 清理当前 delete.yml 自己（即“清理工作流运行记录”）
          cleanup_workflow_runs "清理工作流运行记录"